/* Microchip Technology Inc. and its subsidiaries.  You may use this software 
 * and any derivatives exclusively with Microchip products. 
 * 
 * THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS".  NO WARRANTIES, WHETHER 
 * EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED 
 * WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A 
 * PARTICULAR PURPOSE, OR ITS INTERACTION WITH MICROCHIP PRODUCTS, COMBINATION 
 * WITH ANY OTHER PRODUCTS, OR USE IN ANY APPLICATION. 
 *
 * IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE, 
 * INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND 
 * WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS 
 * BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE.  TO THE 
 * FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS 
 * IN ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF 
 * ANY, THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
 *
 * MICROCHIP PROVIDES THIS SOFTWARE CONDITIONALLY UPON YOUR ACCEPTANCE OF THESE 
 * TERMS. 
 */

/*******************************************************************************
  This source file has NOT been generated by the MHC
 *******************************************************************************/

/* 
 * File:   
 * Author: 
 * Comments:
 * Revision history: 
 */

// *****************************************************************************
// *****************************************************************************
// Section: Included Files 
// *****************************************************************************
// *****************************************************************************

#include "game.h"
#include "UART.h"

// *****************************************************************************
// *****************************************************************************
// Section: Global Data Definitions
// *****************************************************************************
// *****************************************************************************



// *****************************************************************************
// *****************************************************************************
// Section: User Functions
// *****************************************************************************
// *****************************************************************************


// TODO Insert function definitions (right here) to leverage live documentation

int Get_Guess(void) { 

// processing of received data from the user
    char c;
    int n=0, done=0;
    
    while (1) {
        c = UART4_getc();
        UART4_putc(c); // echo back character
        if ((c >= '0') && (c <= '9')) {
            n *= 10;
            n += c-'0';
        } else {
            if (c == '\r')
                return n;
            else
                return ILLEGAL_CHAR;
        }
    }

}

void GuessingGame(void) {

    int guess, number, guesses_left, won=0, num_won=0, num_lost=0, reset_flag=0;
    char buffer[80];
    
    while (1) { // new game
        UART4_puts("\r\nGuessed integer number in the range from 0 to 10.\r\n");
        number = rand() % 10; // random value of number from 0 to 10;
        won = 0;
        for (guesses_left=NUM_GUESSES; (guesses_left>0) && (!won); guesses_left--) {
            sprintf(buffer, "You have %d guesses left.\r\n", guesses_left);
            UART4_puts(buffer);
            UART4_puts("What is this number?? Please type it and press enter.\r\n");
            UART4_puts("If you want to reset counters of wins and losses, type 11.\r\n");
            guess = Get_Guess();
            UART4_puts("\r\n");
            if (guess == ILLEGAL_CHAR) { //cheking correct data
                UART4_puts("That's not a number! You lost your guess.\r\n");
            } 
            else { //checking number which user entered
                if (guess == number) { // user guessed number
                    UART4_puts("Congratulations! You guessed it!\r\n");
                    won = 1;
                } 
                else if (guess < number) { // user didnt guess number
                    UART4_puts("Too low!\r\n");
                } 
                else { // user didnt guess number
                    if (guess == 11) //Reset counters of wins and losses
                    {
                       reset_flag = 1;
                       guesses_left = 0;
                    }
                    else UART4_puts("Too high!\r\n");
                    }
                }
        }
        if (!reset_flag) 
        {
             if (won)  //if user did guess number
                 {
                 num_won++;
                 }
             if (!won) // if user didnt guess number
                {
                sprintf(buffer, "My number was %d.\r\n", number);
                UART4_puts(buffer);
                num_lost++;
                }
            if (num_won == 5) //if user have 5 wins in result gradual guessing
                {
                sprintf(buffer, "[Congratulations, you get jackpot!!!!]:\r\nwon number = %d\r\nlost number = %d\r\n", num_won, num_lost);
                UART4_puts(buffer);  
                num_won = 0;
                num_lost = 0;
                }
            if (num_lost == 5) //if user have 5 loses in result gradual guessing
                {
                sprintf(buffer, "[Sorry, but you don't get jackpot]:\r\nwon number = %d\r\nlost number = %d\r\n", num_won, num_lost);
                UART4_puts(buffer);  
                num_lost = 0;
                num_won = 0;
                } 
        }
        if (reset_flag) 
        {
             num_lost = 0;
             num_won = 0; 
             UART4_puts("Counters of wins and losses were reset!\r\n");
             reset_flag = 0;
            
        }
         // common quantity of wins and loses
         sprintf(buffer, "Won: %d\r\nLost: %d\r\n", num_won, num_lost);
         UART4_puts(buffer);
    }  

}