/* Microchip Technology Inc. and its subsidiaries.  You may use this software 
 * and any derivatives exclusively with Microchip products. 
 * 
 * THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS".  NO WARRANTIES, WHETHER 
 * EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED 
 * WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A 
 * PARTICULAR PURPOSE, OR ITS INTERACTION WITH MICROCHIP PRODUCTS, COMBINATION 
 * WITH ANY OTHER PRODUCTS, OR USE IN ANY APPLICATION. 
 *
 * IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE, 
 * INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND 
 * WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS 
 * BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE.  TO THE 
 * FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS 
 * IN ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF 
 * ANY, THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
 *
 * MICROCHIP PROVIDES THIS SOFTWARE CONDITIONALLY UPON YOUR ACCEPTANCE OF THESE 
 * TERMS. 
 */

/*******************************************************************************
  This source file has NOT been generated by the MHC
 *******************************************************************************/

/* 
 * File:   
 * Author: 
 * Comments:
 * Revision history: 
 */

// *****************************************************************************
// *****************************************************************************
// Section: Included Files 
// *****************************************************************************
// *****************************************************************************

#include "game.h"
#include "UART.h"
void calculate(int x,int y);
void delay(int n);
void random_mas();
// *****************************************************************************
// *****************************************************************************
// Section: Global Data Definitions
// *****************************************************************************
// *****************************************************************************



// *****************************************************************************
// *****************************************************************************
// Section: User Functions
// *****************************************************************************
// *****************************************************************************

// Comment a function definition and leverage automatic documentation 
/**
  <p><b>Function:</b></p>

  <p><b>Summary:</b></p>

  <p><b>Description:</b></p>

  <p><b>Remarks:</b></p>
 */
// TODO Insert function definitions (right here) to leverage live documentation

// d - will die in next step
// a - will born in next step

// size of life-massive
int L_SIZE = 50;
int L_SIZEY = 60;

// variables
char l_mas[50+2][60+2]; // life-massive//char 
//char l_mas[L_SIZE+2][L_SIZEY+2]; // life-massive
int l_i,l_j; // counter's
int l_age=0; // age of population
int l_coef=0; // coefficient for check cell
int buffer;
void GuessingGame(void) {
   // print Hello :)
   
    UART4_puts("\r\nLife  \r\n");
      //	
	// set border
        //
	for(l_i=0;l_i<L_SIZEY+2;l_i++)
		l_mas[0][l_i]=l_mas[L_SIZE+1][l_i]='-';
	for(l_j=0;l_j<L_SIZE+2;l_j++)
		l_mas[l_j][0]=l_mas[l_j][L_SIZEY+1]='|';
	l_mas[L_SIZE+1][0]=l_mas[0][L_SIZEY+1]='+';
	l_mas[0][0]=l_mas[L_SIZE+1][L_SIZEY+1]='+';	
 
     //
		// print life-massive
                //
		for(l_i=0;l_i<L_SIZE+2;l_i++)
		{
			for(l_j=0;l_j<L_SIZEY+2;l_j++)
			{
				if(l_mas[l_i][l_j]=='d')
					l_mas[l_i][l_j]='0'; // amen 8-)
				if(l_mas[l_i][l_j]=='a')
					l_mas[l_i][l_j]='*'; // new cell
				if(l_mas[l_i][l_j]=='0')
                  UART4_putc(' ');
                else
			UART4_putc(l_mas[l_i][l_j]);
            }
			UART4_putc(10);
            UART4_putc(13);
            }
                //
		// calculate next configuration
                //
		for(l_i=1;l_i<L_SIZE+1;l_i++)
		{
			for(l_j=1;l_j<L_SIZEY+1;l_j++)
				calculate(l_i,l_j);
		}
    delay(10000);
    ////////////
}
void calculate(int x,int y)
{// calculate one cell with x,y
    
	switch(l_mas[x][y])
	{
	case 'a':
	case 'd':
	case '+':
	case '|':
	case '-':
	case '0':
	case '*':
		//-------------------------------------//
		l_coef=0;
		if(l_mas[x][y-1]=='*'|| l_mas[x][y-1]=='d') // west
			l_coef++;
		if(l_mas[x-1][y-1]=='*'|| l_mas[x-1][y-1]=='d')// north-west
			l_coef++;
		if(l_mas[x-1][y]=='*'||l_mas[x-1][y]=='d')// north
			l_coef++;
		if(l_mas[x-1][y+1]=='*'||l_mas[x-1][y+1]=='d')// north-east
			l_coef++;
		if(l_mas[x][y+1]=='*'||l_mas[x][y+1]=='d')// east
			l_coef++;
		if(l_mas[x+1][y+1]=='*'||l_mas[x+1][y+1]=='d')// south-east
			l_coef++;
		if(l_mas[x+1][y]=='*'||l_mas[x+1][y]=='d')// south
			l_coef++;
		if(l_mas[x+1][y-1]=='*'||l_mas[x+1][y-1]=='d')// south-west
			l_coef++;
        UART4_putc(l_coef);
		switch(l_coef)
		{
		case 0: 
		case 1: // will die
			if(l_mas[x][y]=='*')
			  l_mas[x][y]='d';
			break;
		//case 2:// stable =)
		//	if(l_mas[x][y]=='*')
		//	l_mas[x][y]='*';
     	//break;
		case 3: // will born
			if(l_mas[x][y]=='0')
				l_mas[x][y]='a';
			break;
		case 4:  // will die
		case 5: 
		case 6: 
		case 7: 
		case 8: 
			if(l_mas[x][y]=='*')
				l_mas[x][y]='d';
			break;
		default:
			break;
		}
		//-------------------------------------//
	}

}

//
// set elements of l_mas zero
//
void null_mas()
{
	for(l_i=1;l_i<L_SIZE+1;l_i++)
	{
		for(l_j=1;l_j<L_SIZEY+1;l_j++)
			l_mas[l_i][l_j]='0';
	}
}

//
// set elements of l_mas via random 
//
void random_mas()
{

  for(l_i=1;l_i<L_SIZE+1;l_i++)
  {
  for(l_j=1;l_j<L_SIZEY+1;l_j++)
  {
      int lotto = rand () % 10 + 1;
      UART4_putc(lotto);
      UART4_putc(10);
      UART4_putc(13);
      if(lotto > 5)
      {
        l_mas[l_i][l_j]='*';
      //  UART4_putc(l_mas[l_i][l_j]);
      }
      else
      {
        l_mas[l_i][l_j]='0';
      }
    }
  }
}

void delay(int n) {
    volatile int i;
    for (i = 0; i < n; i++) {
    }
}